shopware:
  feature:
    flags:
      - name: v6.5.0.0
        default: false
        major: true
      - name: v6.6.0.0
        default: false
        major: true
      - name: FEATURE_NEXT_19501
        default: false
        major: false
        description: "Disables the cart.container function"
        # issue: NEXT-19501
      - name: FEATURE_NEXT_18215
        default: false
        major: true
        description: "Rules are aware of their assignment"
        # issue: NEXT-18215
