parameters:
    messenger.default_transport_name: 'v65'
    env(MESSENGER_TRANSPORT_DSN): 'doctrine://default'
    env(MESSENGER_TRANSPORT_FAILURE_DSN): 'doctrine://default?queue_name=failed'
    env(MAILER_URL): 'null://null'
    env(MESSENGER_TRANSPORT_DSN): "enqueue://default?receiveTimeout=100"

framework:
    esi: true
    trusted_hosts: ~
    fragments: ~
    assets: ~
    session:
        name: 'session-'
        handler_id: ~
        cookie_secure: 'auto'
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.native
    serializer: { enabled: true }
    secret: "%env(APP_SECRET)%"
    validation:
        enable_annotations: true
    default_locale:  en_GB
    http_method_override: true
    mailer:
        message_bus: false
        dsn: '%env(MAILER_URL)%'
    php_errors:
        log: true
    cache:
        prefix_seed: "%kernel.cache.hash%"
        app: cache.adapter.filesystem
        pools:
            cache.object:
                default_lifetime: 172800
                adapter: cache.app
                tags: cache.tags
            cache.http:
                default_lifetime: 172800
                adapter: cache.app
                tags: cache.tags
            cache.tags:
                adapter: cache.app
            cache.rate_limiter:
                adapter: cache.app
    messenger:
        failure_transport: failed
        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        transports:
<<<<<<< HEAD
            default:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
        default_bus: messenger.bus.shopware
        buses:
            messenger.bus.shopware:
                middleware:
                    - Shopware\Core\Framework\MessageQueue\Middleware\RetryMiddleware
=======
            failed: "%env(MESSENGER_TRANSPORT_FAILURE_DSN)%"
            v65:
                dsn: "%env(MESSENGER_TRANSPORT_DSN)%"
                serializer: messenger.transport.symfony_serializer
                retry_strategy:
                    max_retries: 3
                    delay: 1000
                    multiplier: 2
                    max_delay: 0

        routing:
            'Shopware\Core\Framework\MessageQueue\AsyncMessageInterface': v65
>>>>>>> 7acb0a27ce (NEXT-21456 - Remove enqueue bundle and all decorations of symfony messenger component. Use json serialisation for message queue instead of php serialized objects)

sensio_framework_extra:
    router:
        annotations: false
